{{- if and .Values.ingress.enabled .Values.enable_tabix }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "clickhouse.tabix_name" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "clickhouse.tabix_name" . }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "clickhouse.tabix_name" . }}
          servicePort: {{ .Values.tabix.service.port }}
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "clickhouse.name" . }}
          servicePort: {{ .Values.service.port }}
{{- if .Values.ingress.enable_https }}
  tls:
  - hosts:
    - {{ .Values.ingress.tabix_host }}
    secretName: tabix
{{- end }}
{{- end }}