{{- if and .Values.ingress.enabled .Values.enable_tabix }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "clickhouse.tabix_name" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "clickhouse.tabix_name" . }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.tabix_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: tabix
          servicePort: http
{{- if .Values.ingress.enable_https }}
  tls:
  - hosts:
    - {{ .Values.ingress.tabix_host }}
    secretName: tabix
{{- end }}
{{- end }}